package ros

// ServiceType defines the interface that the code created/autogenerated
// for any service definitions should implement.
type ServiceType interface {
	MD5Sum() string
	Name() string
	RequestType() MessageType
	ResponseType() MessageType
	NewService() Service
}

// Service defines the interface that the code created/autogenerated
// for any service definitions should implement
type Service interface {
	ReqMessage() Message
	ResMessage() Message
}
